export const REQUEST_PROFILES_SUCCESS = 'APP/REQUEST_PROFILES_SUCCESS';
export const REQUEST_PROFILES_FAIL = 'APP/REQUEST_PROFILES_FAIL';
export const REQUESTING_PROFILES = 'APP/REQUESTING_PROFILES';
export const REQUESTING_INIT = 'APP/REQUESTING_INIT';
export const REQUEST_INIT_SUCCESS = 'APP/REQUEST_INIT_SUCCESS';
export const REQUEST_INIT_FAIL = 'APP/REQUEST_INIT_FAIL';